---

- name: install misc dev brew applications
  homebrew: name={{ item }} state=latest
  with_items:
    - elixir
    - ghc
    - haskell-stack
    - leiningen

- name: install misc dev cask applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - cathode
    - supercollider
