---

- name: install browser dev cask applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - charles
    - imagealpha
    - imageoptim
    - firefox-developer-edition
    - google-chrome-canary
    - opera-beta
